# Generated by Django 4.2.1 on 2024-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Аукционный товар', 'verbose_name_plural': 'Аукционные товары'},
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Шаг аукционного товара'),
        ),
    ]
