# Generated by Django 4.2.1 on 2024-03-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInf1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, verbose_name='Информация о магазине')),
                ('delivery', models.TextField(blank=True, verbose_name='Информация о доставке и оплате')),
                ('contact', models.TextField(blank=True, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Информация о магазине',
                'verbose_name_plural': 'Информация о магазине',
            },
        ),
    ]
